### ISSUE TITLE
UTF-8 problem with group_by

### ISSUE THREAD

**Issue by YizhouZheng** [hadley/dplyr#1507]
I found the UTF-8  problem still alive in group_by(). (Using the newest dev version. 0.4.3.9000)

See below for reproducible code.

Create a dataframe and make the colnames UTF-8.

```r
library(dplyr)
df <- data.frame(测试=1:3, Eng=2:4)
names(df) <- enc2utf8(names(df))
Encoding(names(df))
[1] "UTF-8" "unknown"
```
select() works.

```r
df %>% select(测试) 
测试
1 1
2 2
3 3
```
group_by doesn't work.

```r
df %>% group_by(测试) #group_by won't work
Error: unknown column '测试'
```

group_by work well under native encoding.

```r
names(df) <- enc2native(names(df))
df %>% select(测试)
测试
1 1
2 2
3 3

df %>% group_by(测试)
Source: local data frame [3 x 2]
Groups: 测试 [3]
测试 Eng
(int) (int)
1 1 2
2 2 3
3 3 4
```

**Comment by romainfrancois** [comment]
I think the real issue is in `Rcpp`. ping @kevinushey, here: https://github.com/hadley/dplyr/blob/master/src/dplyr.cpp#L1450

I'll come up with a workaround, but I think `Rcpp` should have an `Vector::operator[]( const Symbol& )` method that would take into account encoding when searching for the right element that matches a symbol.

**Comment by YizhouZheng** [comment]
Great thanks to @romainfrancois. Looking forward to v0.5

**Comment by romainfrancois** [comment]
I just pushed something. 

@YizhouZheng can you test it please, it should fix the issue but I can't test it on windows right now, where the problem is more likely to happen (the original code in the issue works for me on OS X).

**Comment by YizhouZheng** [comment]
Yeah it was a Windows issue. I tried but it still doesn't work.

See if I followed correct step of getting newest code.

  
I tried downloading and compiling the package by delete original package and run

>  devtools::install_github("hadley/lazyeval")
> devtools::install_github("hadley/dplyr")

> df %>%
>  group_by(测试)

Result was

Error: unknown column '测试'

**Comment by romainfrancois** [comment]
Thanks for trying. I'll have a look next time I run windows

**Comment by yutannihilation** [comment]
I've faced the same problem as this...

I found that the issue is originated from the fact that lazyeval loses the Encoding information after evaluation. More exactly, around here: https://github.com/hadley/dplyr/blob/bd372a4d625b225a40354a9a091b9185c7736dae/R/distinct.R#L46

The code below is an simple example:

```r
# Set encoding as UTF-8
x <- iconv("進捗", to = "UTF-8")
Encoding(x)
#> [1] "UTF-8"

# convert this to lazy_dots
f <- function(.dots, ...) {
  lazyeval::all_dots(.dots, ..., all_named = TRUE)
}

dots <- f(x)
dots
#> $進捗
#> <lazy>
#>   expr: 進捗
#>   env:  <environment: base>
#> 
#> attr(,"class")
#> [1] "lazy_dots"

# The encoding is no more UTF-8!
Encoding(names(dots))
#> [1] "unknown"
```

`select()` avoid this problem by using the indices provided by `lazy_eval()`, instead of the column names like this (The corresponding codes are here: https://github.com/hadley/dplyr/blob/5e2b40ea2f33da4920e5d5666dbb38f033a4be38/R/select-vars.R#L67-L69):

```r
names_list <- setNames(list(1), x)
names_list
#> $`進捗`
#> [1] 1

Encoding(names(names_list))
#> [1] "UTF-8"

lazyeval::lazy_eval(sinchoku_dots, names_list)
#> $進捗
#> [1] 1
```

I'm not quite sure, but I guess the better strategy of `distinct()` and `group_by()` is to use `lazy_eval()` and pass the indices to the C++ impl.

**Comment by romainfrancois** [comment]
@YizhouZheng can you try current dev please. I think this is done now. 
@yutannihilation I like the idea, it would make less calls back to R (which is the way I'm dealing with this now)

**Comment by romainfrancois** [comment]
Closing this now. Please reopen if the problem was not fixed.

**Comment by YizhouZheng** [comment]
Sure, I'm on vacation and don't have access to the environment. I'll check it as soon as I  am back to work.

**Comment by yutannihilation** [comment]
@romainfrancois 
Cool!
I've confirmed the problem I've faced is fixed for now. Thaks!

```r
x <- iconv("種類", to = "UTF-8")
names(iris)[5] <- x
distinct_(iris, x)
#>         種類
#> 1     setosa
#> 2 versicolor
#> 3  virginica
```

**Comment by krlmlr** [comment]
The test `group_by handles encodings (#1507)` fails on my system (Ubuntu 15.10, 3074cf7bfa41c690e).
