### ISSUE TITLE
devtools::install_github() failure

### ISSUE THREAD

**Issue by kevinushey** [hadley/dplyr#2352]
I'm seeing this error when attempting to install `dplyr`:

```
Error: Command failed:
 '/Library/Frameworks/R.framework/Resources/bin/R' CMD INSTALL '/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmpk444km/devtoolsb8bf4c96e5cc/hadley-dplyr-03bba6a'
 * installing to library ‘/Users/kevin/Library/R/3.3/library’
* installing *source* package ‘dplyr’ ...
** libs
Makevars.local:3: RcppExports.d: No such file or directory
Makevars.local:3: address.d: No such file or directory
Makevars.local:3: api.d: No such file or directory
Makevars.local:3: arrange.d: No such file or directory
Makevars.local:3: between.d: No such file or directory
Makevars.local:3: bind.d: No such file or directory
Makevars.local:3: combine_variables.d: No such file or directory
Makevars.local:3: distinct.d: No such file or directory
Makevars.local:3: filter.d: No such file or directory
Makevars.local:3: group.d: No such file or directory
Makevars.local:3: group_indices.d: No such file or directory
Makevars.local:3: hybrid.d: No such file or directory
Makevars.
```

```
 > sessionInfo()
 R version 3.3.2 (2016-10-31)
 Platform: x86_64-apple-darwin13.4.0 (64-bit)
 Running under: macOS Sierra 10.12.2
 
 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
 
 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base
 
 other attached packages:
 [1] testthat_1.0.2  rmarkdown_1.3   knitr_1.15.1    roxygen2_5.0.1
 [5] devtools_1.12.0
 
 loaded via a namespace (and not attached):
  [1] Rcpp_0.12.8         crayon_1.3.2        digest_0.6.11
  [4] withr_1.0.2         rprojroot_1.1       R6_2.2.0
  [7] backports_1.0.4     git2r_0.18.0        magrittr_1.5
 [10] evaluate_0.10       httr_1.2.1          stringi_1.1.2
 [13] curl_2.3            callr_1.0.0.9000    tools_3.3.2
 [16] stringr_1.1.0.9000  pkgload_0.0.0.9000  pkgbuild_0.0.0.9000
 [19] memoise_1.0.0.9001  htmltools_0.3.5
```

**Comment by kevinushey** [comment]
Installation fails locally as well:

```
kevin@cdrv:~/git/dplyr [master]
$ R CMD INSTALL --preclean .
* installing to library ‘/Users/kevin/Library/R/3.3/library’
* installing *source* package ‘dplyr’ ...
** libs
make: *** No rule to make target `/Users/kevin/r/r-devel-sanitizers/library/Rcpp/include/Rcpp/Date.h', needed by `RcppExports.o'.  Stop.
ERROR: compilation failed for package ‘dplyr’
* removing ‘/Users/kevin/Library/R/3.3/library/dplyr’
* restoring previous ‘/Users/kevin/Library/R/3.3/library/dplyr’
```

I notice that for some reason the Make rules are using a separate (currently inactive / non-default) R installation I have.

**Comment by kevinushey** [comment]
And unfortunately now I'm seeing a separate compilation error (after cleaning up the directory a bit)

```
utils.cpp:84:12: error: no matching function for call to 'collapse'
    return collapse<STRSXP>(classes);
           ^~~~~~~~~~~~~~~~
/Users/kevin/Library/R/3.3/library/Rcpp/include/Rcpp/sugar/functions/strings/collapse.h:41:19: note:
      candidate template ignored: invalid explicitly-specified argument for template parameter 'T'
    inline String collapse( const VectorBase<STRSXP,NA,T>& vec ){
                  ^
```

**Comment by krlmlr** [comment]
Works for me with 03bba6a1. The `Makevars.local` file is responsible for creating the `.d` files which record dependencies between source files and headers, it is in `.Rbuildignore` and active only when installing from GitHub.

Which version of Rcpp are you using?

What do you mean by

> the Make rules are using a separate (currently inactive / non-default) R installation I have.

**Comment by kevinushey** [comment]
This bit from the error message surprised me:

```
** libs
make: *** No rule to make target `/Users/kevin/r/r-devel-sanitizers/library/Rcpp/include/Rcpp/Date.h', needed by `RcppExports.o'.  Stop.
```

Note the path to `r-devel-sanitizers`, despite that my 'active' R installation + the one I had been using lives here:

```
$ which R
/usr/local/bin/R
```

What compiler are you using? It's possible that the `collapse()` issue is a clang-specific issue (I'm on macOS).

```
$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
k
```

**Comment by krlmlr** [comment]
1. This looks like a symptom of the rather brittle dependency management with `.d` files. `R CMD INSTALL --preclean .` should fix that. I was looking for a way to make `R CMD INSTALL .` do the right thing if only header files change. I know that `devtools::install()` adds `--preclean`, perhaps just removing all `.o` files if any header changes is the only safe way to do this. Any advice?

2. I'm using gcc 6.2.0 on Ubuntu.

**Comment by kevinushey** [comment]
1. It looks like you're right -- the issue (I think) was that the `.d` files weren't actually cleaned up (perhaps some leftovers were sticking around?) I don't have a better solution beyond just managing this stuff in a `configure` / `configure.win` script.

2. I wasn't able to reproduce with `clang-3.8` on my Ubuntu VM, so this may be an issue specific to the version of `clang` used with macOS. I'll see if I can find someone else who can repro.

**Comment by kevinushey** [comment]
Okay, I think I can reproduce 2. -- it only occurs when compiling with `clang` as well as `-std=c++11` (which I had in my `~/.R/Makevars`). Is that worth filing as a separate issue?

**Comment by krlmlr** [comment]
I think R should be configured by default to explicitly use `-std=c++98` unless the `DESCRIPTION` says different. I [asked on R-Sig-Debian](https://stat.ethz.ch/pipermail/r-sig-debian/2016-November/002628.html) but haven't found support for this idea. If this is an R configuration issue, then nothing needs to be done here. I'm not sure if we're allowed to add `std=...` to `Makeflags` anyway.

Can you please point me to a `configure` solution of yours that manages dependencies?

**Comment by jayhesselberth** [comment]
I had renamed `collapse` to `collapse_string` in the [C++11 fork of dplyr](https://github.com/hadley/dplyr/pull/2230/commits/e59bd4c9b3364a72af4c7e9f09d35dbed19f2e0d), I think it was to address the same `collapse` compilation error as above. At the time I remember thinking it was a namespace problem with `Rcpp::sugar::collapse`.

**Comment by hadley** [comment]
@kevinushey is this resolved now?

**Comment by kevinushey** [comment]
Yes, I think so. Compilation of `dplyr` still fails in C++11 mode, but that's not the mode that `dplyr` is currently intended to be compiled in.

**Comment by kevinushey** [comment]
Nice catch; thanks!
