### ISSUE TITLE
Rename is broken with SQL sources

### ISSUE THREAD

**Issue by iangow** [hadley/dplyr#2583]
The following works fine with the CRAN version of `dplyr`, but not after `devtools::install_github("hadley/dplyr")`. The same issue occurs with a PostgreSQL source.

As can be seen, there is no issue with local sources.

``` r
library(dplyr, warn.conflicts = FALSE)

df <- memdb_frame(x = 1:10, y = 10:1)

df %>%
    rename(z = x)
#> Source:     lazy query [?? x 2]
#> Database:   sqlite 3.11.1 [:memory:]
#> Error in eval(expr, envir, enclos): argument is missing, with no default

df %>%
    collect() %>% 
    rename(z = x)
#> # A tibble: 10 × 2
#>        z     y
#>    <int> <int>
#> 1      1    10
#> 2      2     9
#> 3      3     8
#> 4      4     7
#> 5      5     6
#> 6      6     5
#> 7      7     4
#> 8      8     3
#> 9      9     2
#> 10    10     1
```

**Comment by hadley** [comment]
This is two bugs (now) spread across two packages 😬 I've fixed the first one, and and will fix the other in dbplyr as soon as I've got it building on travis.

**Comment by iangow** [comment]
Hmm. I still get a (different) error after `devtools::install_github("hadley/dplyr")`:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- memdb_frame(x = 1:10, y = 10:1)

df %>%
    rename(z = x)
#> Source:     lazy query [?? x 2]
#> Database:   sqlite 3.11.1 [:memory:]
#> Error: Unknown variables: x.

df %>%
    collect() %>%
    rename(z = x)
#> # A tibble: 10 × 2
#>        z     y
#>    <int> <int>
#> 1      1    10
#> 2      2     9
#> 3      3     8
#> 4      4     7
#> 5      5     6
#> 6      6     5
#> 7      7     4
#> 8      8     3
#> 9      9     2
#> 10    10     1
```

**Comment by hadley** [comment]
Yes, you'll need dbplyr, which is still in flux. If you try again tomorrow it should be good.
